# Generated by Django 2.0.6 on 2020-04-12 01:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdministrators',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('pwd', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_administrators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAlbum',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('announcer', models.CharField(blank=True, max_length=200, null=True)),
                ('num', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TArticle',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('t_url', models.CharField(blank=True, max_length=500, null=True)),
                ('t_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('t_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCount',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('coun', models.CharField(blank=True, max_length=200, null=True)),
                ('t_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLessons',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('t_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPhoto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='img')),
                ('describe_1', models.CharField(blank=True, max_length=200, null=True)),
                ('show_1', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 't_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(upload_to='img')),
                ('autograph', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('spare', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 12, 1, 39, 41, 1947, tzinfo=utc), null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
